### ISSUE TITLE
Where is the beets PDF?

### ISSUE THREAD

**Issue by Keri-Lynn** [Keri-Lynn/content-semantics#1]
@thomasjbradley

Hi Thomas,

Are we supposed to create our own website following the mistakes in markbot or is there a PDF or website we are supposed to get the information from?

Keri

**Comment by thomasjbradley** [comment]
The PDF is in the “Semantics map-out” slide deck from week 4:
https://learn-the-web.algonquindesign.ca/courses/web-dev-1/semantics-map-out/#slide-1
